export const LOADING = "LOADING";

export const USER_SIGNED_IN = "USER_SIGNED_IN";
export const USER_SIGNED_UP = "USER_SIGNED_UP";
export const USER_SIGNED_OUT = "USER_SIGNED_OUT";
export const USER_FAILED = "USER_FAILED";

export const SUBJECTS_LOADED = "SUBJECTS_LOADED";
export const SUBJECT_LOADED = "SUBJECT_LOADED";
export const SUBJECT_ADDED = "SUBJECT_ADDED";
export const SUBJECT_UPDATED = "SUBJECT_UPDATED";
export const SUBJECT_DELETED = "SUBJECT_DELETED";
export const SUBJECT_FAILED = "SUBJECT_FAILED";

export const RESOURCES_LOADED = "RESOURCES_LOADED";
export const RESOURCE_LOADED = "RESOURCE_LOADED";
export const RESOURCE_ADDED = "RESOURCE_ADDED";
export const RESOURCE_UPDATED = "RESOURCE_UPDATED";
export const RESOURCE_DELETED = "RESOURCE_DELETED";
export const RESOURCE_FAILED = "RESOURCE_FAILED";

export const NOTIFICATIONS_LOADED = "NOTIFICATIONS_LOADED";
export const NOTIFICATION_LOADED = "NOTIFICATION_LOADED";
export const NOTIFICATION_ADDED = "NOTIFICATION_ADDED";
export const NOTIFICATION_UPDATED = "NOTIFICATION_UPDATED";
export const NOTIFICATION_DELETED = "NOTIFICATION_DELETED";
export const NOTIFICATION_FAILED = "NOTIFICATION_FAILED";

export const FORUMS_LOADED = "FORUMS_LOADED";
export const FORUM_LOADED = "FORUM_LOADED";
export const FORUM_ADDED = "FORUM_ADDED";
export const FORUM_UPDATED = "FORUM_UPDATED";
export const FORUM_DELETED = "FORUM_DELETED";
export const FORUM_FAILED = "FORUM_FAILED";
